# Generated by Django 4.1.7 on 2023-04-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='abc',
            field=models.BooleanField(blank=True, default=False, help_text='This is my field', null=True, verbose_name='My Field'),
        ),
    ]
