# Generated by Django 4.1.7 on 2023-04-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_registration_mod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='mod',
        ),
        migrations.AddField(
            model_name='registration',
            name='code',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
