# Generated by Django 4.1.7 on 2023-04-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0006_rename_abc_registration_boolean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Pnone No'),
        ),
    ]
