# Generated by Django 4.1.7 on 2023-04-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0007_registration_email_alter_registration_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='Boolean',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='color',
        ),
        migrations.AddField(
            model_name='registration',
            name='Department',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Management Science', 'Management Science'), ('Mechanical Engineering', 'Mechanical Engineering')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='scholarship',
            field=models.BooleanField(blank=True, default=False, help_text='Any Scholarship', null=True, verbose_name='scholarship'),
        ),
    ]
